---
galaxy_info:
  role_name: nginx
  author: "Hendri Olev Serman"
  description: "Nginx web server for multi-environment Ansible setup"
  company: "OIXIO"
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - web
    - nginx
dependencies: []
