all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: localhost
          ansible_connection: local
          server_id: 1
          server_role: primary
        web2:
          ansible_host: localhost
          ansible_connection: local
          server_id: 2
          server_role: secondary
      vars:
        http_port: 80
        https_port: 443
        web_root: "/var/www/html"

    dbservers:
      hosts:
        db1:
          ansible_host: localhost
          ansible_connection: local
          mysql_server_id: 1
          mysql_role: master
      vars:
        mysql_port: 3306
        mysql_data_dir: "/var/lib/mysql"

    development:
      children:
        webservers:
        dbservers:
      vars:
        app_env: "development"
        debug_mode: true
        ssl_enabled: false

    production:
      children:
        webservers:
        dbservers:
      vars:
        app_env: "production"
        debug_mode: false
        ssl_enabled: true
