version: '3.9'

services:
  database:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todos
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app-network

  api:
    build: ./api
    container_name: todo_api
    depends_on:
      - database
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@database:5432/todos
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: nginx:latest
    container_name: todo_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:

